server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: eureka-server